spring:
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:55643/railway
    username: postgres
    password: kyFWResFoNkJshUkfJsYIVyqwqzOSkJz
    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 600000
    pool-name: MyHikariCP
    max-lifetime: 1800000
    connection-timeout: 30000